#!/bin/sh

if ! cargo test; then
    printf "\n"
    echo "Some tests failed; aborting commit"
    exit 1
fi

# -D warnings means deny warnings; docs must build with no warnings

if ! RUSTDOCFLAGS="-D warnings" cargo doc --no-deps; then
  printf "\n"
  echo "Docs don't build correctly; aborting commit"
  exit 1
fi

if ! cargo build; then
    printf "\n"
    echo "Couldn't build; aborting commit"
    exit 1
fi

for FLICK_SRC_FILE in examples/*.fl; do
  if ! target/debug/flick $FLICK_SRC_FILE; then
    printf "\n"
    echo "$FLICK_SRC_FILE does not compile; aborting commit"
    exit 1
  fi
done